# This is a basic workflow to help you get started with Actions

name: hide-file-sh-app

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Init (clone) repo
      uses: actions/checkout@v3

    - name: Current commit hash
      run: |
        echo "Current commit hash value is ${{ github.sha }}"

    - name: Install dependencies
      run: |
        echo 1

    - name: Set permissions to test
      run: |
        chmod +x ./test.sh
    
    - name: Set permissions to script
      run: |
        chmod +x ./hide_file.sh

    - name: Test with bash
      run: |
        ./test.sh
